### PR TITLE
Profile Feature merge into master branch :O

### PR DESCRIPTION
**Pull request by AkashAryal**
### Summary 
It's happening!!!! This PR aims to merge the profile feature that the team has meticulously developed this past year. 

### Test Plan
We have tested each PR into my_reviews_page through our unit tests and manually testing. The branch, `my_reviews_page` has also been tested during our last work session (more testing is nice too so feel free to pull this and leave comments).

`my_reviews_page` branch is deployed on our [staging site](https://cornellreviews-dev.herokuapp.com/)

### CODE REVIEW

**Review by tinaou32 — APPROVED** [review]
Thank you guys for working on this! I really appreciate your time and effort. I looked at my reviews and all of the ones that I wrote were present. I also tested adding a new review to see if the most recent review would show up. The newest review does show up! Something that I noticed was how whenever you go to a class page in order to submit a review of the class that you are looking for, the profile icon on the top right disappears. This can be inconvenient and not very intuitive for users to check their profiles and the reviews they submitted.

**Review by michelleli01 — COMMENTED** [review]
Looks great! Great job everyone for working so hard on this feature. I tested it locally and I cannot submit a review on my desktop because the submit button is cut off on my screen. 
image

**Comment by AkashAryal** [comment]
> Looks great! Great job everyone for working so hard on this feature. I tested it locally and I cannot submit a review on my desktop because the submit button is cut off on my screen. image

Oh yess this is a problem. Maybe we shouod revert this sticky change back.

**Comment by michelleli01** [comment]
> > Looks great! Great job everyone for working so hard on this feature. I tested it locally and I cannot submit a review on my desktop because the submit button is cut off on my screen. image
> 
> Oh yess this is a problem. Maybe we shouod revert this sticky change back.

The submit button appears when I scroll all the way down the page, but I think we should revert sticky back.

**Pull request closed without merging**
