### PR TITLE
linking authentication

### PR DESCRIPTION
**Pull request by michelleli01**
### Summary 
This endpoint retrieves the user email, total number of reviews, and total number of reviews helpful from the user information stored in the database and displays the information in replacement of the hardcoded numbers implemented on the left profile page..

This pull request is the first step towards implementing feature Foo

- [x] display verified user email
- [x] created endpoint to retrieve verified email based on session token
- [x] display total number of user reviews
- [x] display total number of likes user reviews from their reviews

### Test Plan 
I ran the code on my laptop and the data displays on my browser.
image

### Linter Warnings 

Before this PR (i.e. on the main branch), there are X linter warnings. After my PR, there are Y.

### CODE REVIEW

**Comment by jack-farley** [comment]
Did you mean to merge this into my_reviews_page Michelle? Looks like it has all the updates from that

**Comment by michelleli01** [comment]
> Did you mean to merge this into my_reviews_page Michelle? Looks like it has all the updates from that

Oops, yeah my bad I just changed it to my_reviews_page

**Review by AnkitLakkapragada — COMMENTED** [review]
Looks good! I liked the improved readability in endpoints.ts. I'm a little confused on how getViewsTotal() is going to work in Profile.tsx but I'm looking forward to seeing how you implement it.

**Review by jack-farley — COMMENTED** [review]
This all looks good to me, great job! I agree with Ankit that getting the number of views might be a little tough to implement. Maybe we just store the number of views each review has and then increment that number every time a review is fetched from the database?

**Pull request closed without merging**
